{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such column: jobId","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE INDEX `approvals_job_id` ON `approvals` (`jobId`)"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE INDEX `approvals_job_id` ON `approvals` (`jobId`)"},"sql":"CREATE INDEX `approvals_job_id` ON `approvals` (`jobId`)","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addIndex (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:586:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1427:7)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:46:5)","timestamp":"2025-09-24 15:11:34"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: Cannot add a UNIQUE column","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:430:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1373:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:46:5)","timestamp":"2025-09-24 15:12:42"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: Cannot add a UNIQUE column","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:430:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1373:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:46:5)","timestamp":"2025-09-24 15:12:48"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: Cannot add a UNIQUE column","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;"},"sql":"ALTER TABLE `approvals` ADD `jobId` VARCHAR(255) NOT NULL UNIQUE;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:430:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1373:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:46:5)","timestamp":"2025-09-24 15:13:44"}
{"code":"LIMIT_UNEXPECTED_FILE","field":"file","level":"error","message":"Unexpected field","name":"MulterError","stack":"MulterError: Unexpected field\n    at wrappedFileFilter (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\index.js:40:19)\n    at Multipart.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\lib\\make-middleware.js:109:7)\n    at Multipart.emit (node:events:519:28)\n    at HeaderParser.cb (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:358:14)\n    at HeaderParser.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:162:20)\n    at SBMH.ssCb [as _cb] (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:394:37)\n    at feed (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:248:10)\n    at SBMH.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:104:16)\n    at Multipart._write (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:567:19)\n    at writeOrBuffer (node:internal/streams/writable:572:12)","storageErrors":[],"timestamp":"2025-09-25 19:26:41"}
{"code":"LIMIT_UNEXPECTED_FILE","field":"file","level":"error","message":"Unexpected field","name":"MulterError","stack":"MulterError: Unexpected field\n    at wrappedFileFilter (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\index.js:40:19)\n    at Multipart.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\lib\\make-middleware.js:109:7)\n    at Multipart.emit (node:events:519:28)\n    at HeaderParser.cb (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:358:14)\n    at HeaderParser.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:162:20)\n    at SBMH.ssCb [as _cb] (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:394:37)\n    at feed (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:248:10)\n    at SBMH.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:104:16)\n    at Multipart._write (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:567:19)\n    at writeOrBuffer (node:internal/streams/writable:572:12)","storageErrors":[],"timestamp":"2025-09-25 19:27:44"}
{"code":"LIMIT_UNEXPECTED_FILE","field":"file","level":"error","message":"Unexpected field","name":"MulterError","stack":"MulterError: Unexpected field\n    at wrappedFileFilter (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\index.js:40:19)\n    at Multipart.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\multer\\lib\\make-middleware.js:109:7)\n    at Multipart.emit (node:events:519:28)\n    at HeaderParser.cb (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:358:14)\n    at HeaderParser.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:162:20)\n    at SBMH.ssCb [as _cb] (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:394:37)\n    at feed (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:248:10)\n    at SBMH.push (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\streamsearch\\lib\\sbmh.js:104:16)\n    at Multipart._write (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\busboy\\lib\\types\\multipart.js:567:19)\n    at writeOrBuffer (node:internal/streams/writable:572:12)","storageErrors":[],"timestamp":"2025-09-25 19:29:09"}
{"level":"error","message":"Error creating approval: Cannot read properties of undefined (reading 'toLocaleDateString')","stack":"TypeError: Cannot read properties of undefined (reading 'toLocaleDateString')\n    at sendApprovalEmail (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\services\\email.service.ts:54:144)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\routes\\approval.routes.ts:93:11)","timestamp":"2025-09-25 19:31:33"}
{"fileInfo":{"fieldname":"file","filename":"3609211e-3bbc-4087-8e77-63b5e2ea1ed2-_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\3609211e-3bbc-4087-8e77-63b5e2ea1ed2-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892},"files":[{"destination":"../uploads","encoding":"7bit","fieldname":"file","filename":"3609211e-3bbc-4087-8e77-63b5e2ea1ed2-_00001_Les Essarts 25-26 Flyer.pdf","mimetype":"application/pdf","originalname":"_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\3609211e-3bbc-4087-8e77-63b5e2ea1ed2-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892}],"level":"error","message":"Cannot read properties of undefined (reading 'toLocaleDateString')","requestBody":{"customerEmail":"d.huhn@thamm.de","customerName":"Daniel Huhn","fileName":"Les Essarts 25-26 Flyer.pdf","jobId":"Les Essarts 25-26 Flyer.pdf_1758821943938","metadata":"{\"fileName\":\"Les Essarts 25-26 Flyer.pdf\",\"originalPath\":\"C:/Users/switch/AppData/Local/Temp/FixtureTest00/inFolder2/_00001_Les Essarts 25-26 Flyer.pdf\",\"submitTime\":\"2025-09-25T19:39:03Z\"}"},"stack":"TypeError: Cannot read properties of undefined (reading 'toLocaleDateString')\n    at sendApprovalEmail (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\services\\email.service.ts:54:144)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\routes\\approval.routes.ts:93:11)","timestamp":"2025-09-25 19:39:04"}
{"fileInfo":{"fieldname":"file","filename":"f1861d92-1619-4d70-9492-eba9293f6681-_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\f1861d92-1619-4d70-9492-eba9293f6681-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892},"files":[{"destination":"../uploads","encoding":"7bit","fieldname":"file","filename":"f1861d92-1619-4d70-9492-eba9293f6681-_00001_Les Essarts 25-26 Flyer.pdf","mimetype":"application/pdf","originalname":"_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\f1861d92-1619-4d70-9492-eba9293f6681-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892}],"level":"error","message":"WHERE parameter \"jobId\" has invalid \"undefined\" value","requestBody":{"customerEmail":"d.huhn@thamm.de","customerName":"Daniel Huhn","fileName":"Les Essarts 25-26 Flyer.pdf","jobId":"Les Essarts 25-26 Flyer.pdf_1758822074251","metadata":"{\"fileName\":\"Les Essarts 25-26 Flyer.pdf\",\"originalPath\":\"C:/Users/switch/AppData/Local/Temp/FixtureTest00/inFolder2/_00001_Les Essarts 25-26 Flyer.pdf\",\"submitTime\":\"2025-09-25T19:41:14Z\"}"},"stack":"Error: WHERE parameter \"jobId\" has invalid \"undefined\" value\n    at SQLiteQueryGenerator.whereItemQuery (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-generator.js:2451:13)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-generator.js:2440:25)\n    at Array.forEach (<anonymous>)\n    at SQLiteQueryGenerator.whereItemsQuery (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-generator.js:2438:35)\n    at SQLiteQueryGenerator.getWhereConditions (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-generator.js:2866:19)\n    at SQLiteQueryGenerator.selectQuery (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-generator.js:1466:28)\n    at SQLiteQueryInterface.select (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1002:27)\n    at Function.findAll (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1824:47)\n    at async Function.findOne (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async getApproval (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\services\\approval.service.ts:48:10)","timestamp":"2025-09-25 19:41:14"}
{"address":"127.0.0.1","code":"ESOCKET","command":"CONN","errno":-4078,"level":"error","message":"Failed to send approval email: connect ECONNREFUSED 127.0.0.1:587","port":587,"stack":"Error: connect ECONNREFUSED 127.0.0.1:587\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)","syscall":"connect","timestamp":"2025-09-25 19:42:11"}
{"fileInfo":{"fieldname":"file","filename":"a260492f-aea4-437e-b847-3e8e1f30c4bf-_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\a260492f-aea4-437e-b847-3e8e1f30c4bf-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892},"files":[{"destination":"../uploads","encoding":"7bit","fieldname":"file","filename":"a260492f-aea4-437e-b847-3e8e1f30c4bf-_00001_Les Essarts 25-26 Flyer.pdf","mimetype":"application/pdf","originalname":"_00001_Les Essarts 25-26 Flyer.pdf","path":"..\\uploads\\a260492f-aea4-437e-b847-3e8e1f30c4bf-_00001_Les Essarts 25-26 Flyer.pdf","size":4939892}],"level":"error","message":"connect ECONNREFUSED 127.0.0.1:587","requestBody":{"customerEmail":"d.huhn@thamm.de","customerName":"Daniel Huhn","fileName":"Les Essarts 25-26 Flyer.pdf","jobId":"Les Essarts 25-26 Flyer.pdf_1758822130958","metadata":"{\"fileName\":\"Les Essarts 25-26 Flyer.pdf\",\"originalPath\":\"C:/Users/switch/AppData/Local/Temp/FixtureTest00/inFolder2/_00001_Les Essarts 25-26 Flyer.pdf\",\"submitTime\":\"2025-09-25T19:42:10Z\"}"},"stack":"Error: connect ECONNREFUSED 127.0.0.1:587\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)","timestamp":"2025-09-25 19:42:11"}
{"address":"127.0.0.1","code":"ESOCKET","command":"CONN","errno":-4078,"level":"error","message":"Failed to send approval email: connect ECONNREFUSED 127.0.0.1:587","port":587,"stack":"Error: connect ECONNREFUSED 127.0.0.1:587\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)","syscall":"connect","timestamp":"2025-09-25 19:45:07"}
{"error":"connect ECONNREFUSED 127.0.0.1:587","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 19:52:12"}
{"error":"connect ECONNREFUSED 127.0.0.1:587","jobId":"Les Essarts 25-26 Flyer.pdf_1758823202179","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 20:00:02","to":"d.huhn@thamm.de"}
{"error":"connect ECONNREFUSED 127.0.0.1:587","jobId":"Les Essarts 25-26 Flyer.pdf_1758823314844","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 20:01:54","to":"d.huhn@thamm.de"}
{"actualTransporterConfig":{"host":"mail.thamm.de","port":587,"user":"thamm\\switch"},"error":"Message failed: 550 5.7.60 SMTP; Client does not have permissions to send as this sender","jobId":"Les Essarts 25-26 Flyer.pdf_1758823624550","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 20:07:05","to":"d.huhn@thamm.de"}
{"actualTransporterConfig":{"host":"mail.thamm.de","port":587,"user":"thamm\\switch"},"error":"Message failed: 550 5.7.60 SMTP; Client does not have permissions to send as this sender","jobId":"Les Essarts 25-26 Flyer.pdf_1758823683680","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 20:08:04","to":"d.huhn@thamm.de"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: approvals_backup","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-25 20:48:20"}
{"errors":[{"instance":null,"message":"token must be unique","origin":"DB","path":"token","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["token"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-25 20:48:46"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: approvals_backup","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-25 20:48:58"}
{"errors":[{"instance":null,"message":"token must be unique","origin":"DB","path":"token","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["token"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-25 20:49:03"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: approvals_backup","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-25 20:56:00"}
{"actualTransporterConfig":{"host":"mail.thamm.de","port":587,"user":"thamm\\switch"},"error":"Invalid login: 451 4.7.0 Temporary server error. Please try again later. PRX5 ","jobId":"Les Essarts 25-26 Flyer.pdf_1758835149800","level":"error","message":"Failed to send approval email:","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-25 23:19:23","to":"d.huhn@thamm.de"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: duplicate column name: rejectedBy","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `rejectedBy` VARCHAR(255);"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"ALTER TABLE `approvals` ADD `rejectedBy` VARCHAR(255);"},"sql":"ALTER TABLE `approvals` ADD `rejectedBy` VARCHAR(255);","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:430:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1373:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-26 13:24:50"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: main.orders","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-26 13:24:50"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: orders","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:79:5)","timestamp":"2025-09-26 13:33:50"}
{"errors":[{"instance":null,"message":"token must be unique","origin":"DB","path":"token","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["token"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 13:35:01"}
{"0":"a","1":"p","10":"e","11":"l","12":"o","13":"a","14":"d","15":" ","16":"i","17":"s","18":" ","19":"n","2":"p","20":"o","21":"t","22":" ","23":"a","24":" ","25":"f","26":"u","27":"n","28":"c","29":"t","3":"r","30":"i","31":"o","32":"n","4":"o","5":"v","6":"a","7":"l","8":".","9":"r","level":"error","message":"Failed to reload approval:","timestamp":"2025-09-26 14:13:28"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: orders_backup","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"DROP TABLE `orders_backup`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"DROP TABLE `orders_backup`;"},"sql":"DROP TABLE `orders_backup`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:15:16"}
{"errors":[{"instance":null,"message":"jobId must be unique","origin":"DB","path":"jobId","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["jobId"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;"},"sql":"INSERT INTO `approvals_backup` SELECT `id`, `jobId`, `fileName`, `filePath`, `customerEmail`, `customerName`, `status`, `token`, `comments`, `approvedBy`, `approvedAt`, `rejectedReason`, `metadata`, `expiresAt`, `switchFlowId`, `switchJobId`, `createdAt`, `updatedAt`, `rejectedBy`, `rejectedAt`, `orderNumber`, `orderId`, `material`, `positionNumber` FROM `approvals`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:15:40"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: no such table: orders_backup","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `orders` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders_backup`;"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"INSERT INTO `orders` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders_backup`;"},"sql":"INSERT INTO `orders` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders_backup`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:15:47"}
{"level":"error","message":"Failed to start server: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","name":"SequelizeForeignKeyConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"parameters":{},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"sql":"DROP TABLE `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:01"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:01"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:01"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:16"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:16"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:16"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:31"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:23:45"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:25:47"}
{"level":"error","message":"Failed to start server: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","name":"SequelizeForeignKeyConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"parameters":{},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"sql":"DROP TABLE `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:37:07"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:37:07"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:37:07"}
{"level":"error","message":"Failed to start server: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","name":"SequelizeForeignKeyConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"parameters":{},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"sql":"DROP TABLE `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:40:00"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:40:00"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:40:00"}
{"level":"error","message":"Failed to start server: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","name":"SequelizeForeignKeyConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"parameters":{},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"DROP TABLE `orders`;"},"sql":"DROP TABLE `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:41:25"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:41:25"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:41:25"}
{"errors":[{"instance":null,"message":"orderNumber must be unique","origin":"DB","path":"orderNumber","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":null}],"fields":["orderNumber"],"level":"error","message":"Failed to start server: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"parent":{"code":"SQLITE_CONSTRAINT","errno":19,"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;"},"sql":"INSERT INTO `orders_backup` SELECT `id`, `orderNumber`, `customerEmail`, `customerName`, `lastEmailSent`, `emailThrottleMinutes`, `status`, `createdAt`, `updatedAt` FROM `orders`;","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.changeColumn (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query-interface.js:48:40)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1408:11)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:81:5)","timestamp":"2025-09-26 14:41:25"}
{"error":"import_nodemailer.default.createTransporter is not a function","level":"error","message":"Failed to send order collection email:","orderNumber":"661761","smtpConfig":{"host":"mail.thamm.de","port":"587","user":"thamm\\switch"},"timestamp":"2025-09-26 14:55:39","to":"d.huhn@thamm.de"}
{"fileInfo":{"fieldname":"file","filename":"7a2fc91f-aaeb-46ac-9e1c-fb2dde49edcf-_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","path":"..\\uploads\\7a2fc91f-aaeb-46ac-9e1c-fb2dde49edcf-_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","size":1599794},"files":[{"destination":"../uploads","encoding":"7bit","fieldname":"file","filename":"7a2fc91f-aaeb-46ac-9e1c-fb2dde49edcf-_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","mimetype":"application/pdf","originalname":"_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","path":"..\\uploads\\7a2fc91f-aaeb-46ac-9e1c-fb2dde49edcf-_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","size":1599794}],"level":"error","message":"SQLITE_ERROR: no such column: orderToken","requestBody":{"customerEmail":"d.huhn@thamm.de","customerName":"Daniel Huhn","fileName":"661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf","jobId":"661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf_1758892462801","material":"Testmaterial","metadata":"{\"fileName\":\"661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf\",\"material\":\"Testmaterial\",\"orderNumber\":\"661761\",\"originalPath\":\"C:/Users/switch/AppData/Local/Temp/FixtureTest01/inFolder2/_00001_661761_1_1__9591079_Zaunschild_HWS_QR_15x10_DE.pdf\",\"positionNumber\":1,\"submitTime\":\"2025-09-26T15:14:22Z\"}","orderNumber":"661761","positionNumber":"1"},"stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.select (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Function.findOrCreate (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:2403:21)\n    at async OrderService.findOrCreateOrder (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\services\\order.service.ts:32:30)","timestamp":"2025-09-26 15:14:22"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: index approvals_status already exists","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE INDEX `approvals_status` ON `approvals` (`status`)"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE INDEX `approvals_status` ON `approvals` (`status`)"},"sql":"CREATE INDEX `approvals_status` ON `approvals` (`status`)","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addIndex (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:586:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1427:7)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:87:5)","timestamp":"2025-09-26 15:14:44"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: index orders_order_number already exists","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)"},"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addIndex (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:586:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1427:7)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:87:5)","timestamp":"2025-09-26 15:17:26"}
{"level":"error","message":"Failed to start server: SQLITE_ERROR: index orders_order_number already exists","name":"SequelizeDatabaseError","original":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)"},"parameters":{},"parent":{"code":"SQLITE_ERROR","errno":1,"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)"},"sql":"CREATE UNIQUE INDEX `orders_order_number` ON `orders` (`orderNumber`)","stack":"Error\n    at Database.<anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:236:27)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:50)\n    at new Promise (<anonymous>)\n    at Query.run (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\sqlite\\query.js:234:12)\n    at <anonymous> (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:650:28)\n    at async SQLiteQueryInterface.addIndex (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:586:12)\n    at async Function.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\model.js:1427:7)\n    at async Sequelize.sync (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async startServer (C:\\Users\\dhuhn\\PyProjects\\ThammApprove\\backend\\src\\index.ts:87:5)","timestamp":"2025-09-26 15:17:26"}
